#!/usr/bin/env python
# vim: syntax=python

# Freeswitch (Phone) agent

import os
import gc
import subprocess
import sys

script_dir = os.path.dirname(os.path.realpath(__file__))

allowed_checks = [
    "show-status",
    "show-calls-count",
    "show-registrations-count",
    "sofia-status-internal",
    "sofia-status-external",
    "sofia-status-profile-internal-failed-calls-in",
    "sofia-status-profile-internal-failed-calls-out"
    ]

def checkmk_output(data):
    for line in data:
        output += "\n%s" % line
    return output

def main():
    print("<<<freeswitch>>>")
    for cmd in allowed_checks:
        modcmd = cmd.replace("-", " ")

        p = subprocess.Popen(["/usr/bin/fs_cli", "-x", modcmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        out, err = p.communicate()
        print("<<" + cmd + ">>")
        print(out)

main()
